spring:
    ## DB接続情報
    dataSource:
        url: jdbc:mysql://okozukai-db.cgzqjfdvnh64.ap-northeast-1.rds.amazonaws.com:3306/okozukai
        username: okozukaiadmin
        password: lknuve7gAre%
        driver-class-name: com.mysql.cj.jdbc.Driver
    ## ホットデプロイ設定
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    ## セッション管理設定
    #session:
        #store-type:redis# サーバー設定
server:
    port: 5000
